import { motion } from "framer-motion";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Animation from "../components/animation";
import Variants from "../components/variants";

export default function Home() {
	const articles = [
		{ id: 1, title: "Great times 1", excerpt: "Await you" },
		{ id: 2, title: "Great times 2", excerpt: "Await you" },
		{ id: 3, title: "Great times 3", excerpt: "Await you" },
		{ id: 4, title: "Great times 4", excerpt: "Await you" },
		{ id: 5, title: "Great times 5", excerpt: "Await you" },
		{ id: 6, title: "Great times 6", excerpt: "Await you" },
	];

	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<div className={styles.articles}>
					{articles.map((article, i) => (
						<motion.div
							key={article.id}
							className={styles.article}
							initial={{
								opacity: 0,
								translateX: i % 2 === 0 ? -50 : 50,
								translateY: -50,
							}}
							animate={{ opacity: 1, translateX: 0, translateY: 0 }}
							transition={{ duration: 0.3, delay: i * 0.2 }}
						>
							<h2>{article.title}</h2>
							<p>{article.excerpt}</p>
						</motion.div>
					))}
				</div>
				<Animation />
				<Variants />
			</main>
		</div>
	);
}
